import { Anthropic } from '@anthropic-ai/sdk';
import { Artefact, VAFFramework } from '../types/index';
import { logger } from '../logger';

const client = new Anthropic();

export const validationAgent = {
  async validate(artefact: Artefact, framework: VAFFramework, relatedArtefacts?: Artefact[]): Promise<boolean> {
    const startTime = Date.now();

    const systemPrompt = buildSystemPrompt(framework);

    const relatedContext =
      relatedArtefacts && relatedArtefacts.length > 0
        ? `\n\nRelated artefacts (for cross-alignment checking):\n${relatedArtefacts.map(a => `${a.type}: ${a.content.slice(0, 500)}`).join('\n\n')}`
        : '';

    try {
      const response = await client.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 2000,
        system: systemPrompt,
        messages: [
          {
            role: 'user',
            content: `Validate this ${artefact.type} artefact against VAF correspondence rules and quality standards.

## Artefact to Validate

Type: ${artefact.type}
Generated by: ${artefact.metadata.generatedBy}

Content:
${artefact.content}
${relatedContext}

## Validation Task

1. Check structure compliance (ISO 42010 for ${artefact.type})
2. Check tone consistency (forensic/declarative for governance, narrative for strategy, technical for design)
3. Check correspondence rules (alignment with other artefacts if provided)
4. Check VAF concept application (Integrity Gap, Decision Latency, Velocity of Truth, etc.)
5. Check formatting (valid Markdown)

Respond ONLY with JSON in this format:
{
  "valid": true/false,
  "score": 0-100,
  "issues": ["issue 1", "issue 2"],
  "recommendations": ["fix 1", "fix 2"],
  "details": "Detailed explanation of validation result"
}`,
          },
        ],
      });

      const content = response.content[0];
      if (content.type !== 'text') {
        throw new Error('Unexpected response type from Claude');
      }

      // Parse JSON response (strip markdown fences if present)
      const cleaned = content.text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
      const result = JSON.parse(cleaned);
      const isValid = result.valid === true;

      const duration = Date.now() - startTime;
      logger.info(
        {
          requestId: artefact.metadata.requestId,
          type: artefact.type,
          valid: isValid,
          score: result.score,
          issues: result.issues?.length || 0,
          durationMs: duration,
        },
        `Validation ${isValid ? 'passed' : 'failed'}`
      );

      if (!isValid && result.issues && result.issues.length > 0) {
        logger.warn({ issues: result.issues }, `Validation issues for ${artefact.type}`);
      }

      // Mark validation result in artefact metadata
      artefact.metadata.validationPassed = isValid;

      return isValid;
    } catch (error) {
      logger.error(
        {
          requestId: artefact.metadata.requestId,
          type: artefact.type,
          error: error instanceof Error ? error.message : String(error),
        },
        'Validation failed with error'
      );
      return false;
    }
  },
};

function buildSystemPrompt(framework: VAFFramework): string {
  return `You are the Validation Agent for the Velocity Architecture Framework (VAF) v2.

Your role: Validate that generated artefacts comply with VAF rules, correspondence constraints, and quality standards.

## VAF Framework Context

### Correspondence Rules (Must Check)
${framework.correspondenceRules}

### Foundation Layer (Guiding Principles)
${framework.foundation.slice(0, 2000)}...

## Validation Criteria

### Structure Compliance
- Governance (VP1): Must include Decision Authority, Governance Drag Analysis, Compliance Mappings, Altitude Collapse Risk
- Strategy (VP2): Must include Options, Trade-offs, Sequencing Rationale, Investment Profile
- Design (VP3): Must include Context, Decision, Rationale, Consequences, Fitness Functions

### Tone Compliance
- Governance: Forensic, declarative, no hedging
- Strategy: Narrative-driven, evidence-based
- Design: Technical, precise, implementation-focused

### Correspondence Rules
- Governance must establish decision authority framework
- Strategy must align with governance constraints
- Design must implement strategic decisions and governance requirements

### VAF Concept Application
- Must apply Integrity Gap, Decision Latency, Velocity of Truth where relevant
- Must reference governance drag where applicable
- Must assess altitude collapse risk (governance vs. operations alignment)

## Validation Rules

1. If critical structure elements are missing, mark as INVALID
2. If tone is inconsistent, mark as INVALID
3. If governance/strategy/design misalignment exists, mark as INVALID
4. If VAF concepts are not referenced, mark as INVALID but note as a warning
5. Provide score 0-100 based on compliance percentage
6. Always list specific issues and recommendations

## Output Format

Respond ONLY with valid JSON. No preamble. No explanation.`;
}
